# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.4.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: info@thinkube.com
author_name: Alejandro Martínez Corriá and the Thinkube contributors
has_binder: false
has_settings: true
kind: frontend
labextension_name: tk-ai-extension
project_short_description: AI assistant extension for tk-ai lab (Thinkube JupyterHub)
python_name: tk_ai_extension
repository: https://github.com/thinkube/tk-ai-extension
test: true

